# world settings
json_dir: /../HouseExpo/json
png_dir: /../assets/png
map_id_train_set: /assets/maps/train/filepaths.txt
map_id_eval_set: /../assets/mapset_eval.txt

# [GC,LC,NC]
comm_mode: GC

# robots settings
robots:
  number: 3
  robotRadius: 0
  sensorRange: 4
  startPose:
    x: 0
    y: 0
  resetRandomPose: 1
  probabilityOfFailedScan: -1
  probabilityOfFailedAction: -1
  probabilityOfFailedCommunication: -1
  w1: 0.00002
  w2: 0.001
  w3: 0.1

# others
stateSize:
  x: 145
  y: 145

# frontiers
frontiers:
  number: 8

# map
map:
  y: 200
  x: 200

# color
color:
  # free: 10
  # obstacle: 100
  # uncertain: 55
  # self: 200
  # others: 150
  # fog: 255

  free: 0
  obstacle: 100
  uncertain: 50
  self: 200
  others: 150
  fog: 255

hyperparams:
  alpha1: 0.01
  alpha2: 0.01

  max_steps: 1000
  timestep_decay: 1.000007
  training_frequency: 100
  lr: 0.0001
  noise_mag: 10

  checkpoint_frequency: 100

